DROP DATABASE IF EXISTS SCHOOL_RESTAURANT_DB;

CREATE DATABASE SCHOOL_RESTAURANT_DB DEFAULT CHARACTER SET utf8;

USE SCHOOL_RESTAURANT_DB;

DROP TABLE IF EXISTS tbl_identity;
DROP TABLE IF EXISTS tbl_user;
DROP TABLE IF EXISTS tbl_dish;
DROP TABLE IF EXISTS tbl_order;
DROP TABLE IF EXISTS tbl_student_order;
DROP TABLE IF EXISTS tbl_canteen_order;

-- TABLE IDENTITY --
CREATE TABLE tbl_identity(
  TI_ID INT AUTO_INCREMENT,
  TI_NAME VARCHAR(20) NOT NULL,
  TI_DETAIL VARCHAR(50),
  PRIMARY KEY(TI_ID)
) AUTO_INCREMENT=1001 DEFAULT CHARSET=utf8;

-- TABLE USER --
CREATE TABLE tbl_user(
  TU_ID INT AUTO_INCREMENT,
  TU_NAME VARCHAR(50) NOT NULL,
  TU_PWD VARCHAR(32) NOT NULL,
  TU_ADDRESS VARCHAR(100) NOT NULL,
  TU_DATE DATE NOT NULL,
  TI_ID INT NOT NULL,
  TU_DETAIL VARCHAR(100),
  DELETE_FLG TINYINT(1) DEFAULT '0' COMMENT '0：未删除 1：已删除',
  PRIMARY KEY(TU_ID),
  FOREIGN KEY(TI_ID) REFERENCES tbl_identity(TI_ID)
) ENGINE=InnoDB AUTO_INCREMENT=1001 DEFAULT CHARSET=utf8;

-- TABLE DISH --
CREATE TABLE tbl_dish(
  TD_ID INT AUTO_INCREMENT,
  TD_NAME VARCHAR(20) NOT NULL,
  TD_IMG VARCHAR(50),
  TU_ID INT NOT NULL,
  TD_PRICE VARCHAR(10) NOT NULL,
  TD_DATE DATE NOT NULL,
  TD_DETAIL VARCHAR(100),
  DELETE_FLG TINYINT(1) DEFAULT '0',
  PRIMARY KEY(TD_ID),
  FOREIGN KEY(TU_ID) REFERENCES tbl_user(TU_ID)
) ENGINE=InnoDB AUTO_INCREMENT=1001 DEFAULT CHARSET=utf8;

-- TABLE ORDER --
CREATE TABLE tbl_order(
  TO_ID INT AUTO_INCREMENT,
  TO_NO VARCHAR(20) NOT NULL,
  TO_PRICE VARCHAR(10) NOT NULL,
  TO_DATE DATE NOT NULL,
  STATUS_FLG TINYINT(1) DEFAULT '0' COMMENT '0：未完成 1：已完成',
  DELETE_FLG TINYINT(1) DEFAULT '0',
  PRIMARY KEY(TO_ID)
) ENGINE=InnoDB AUTO_INCREMENT=100001 DEFAULT CHARSET=utf8;


-- TABLE USER&ORDER --
CREATE TABLE tbl_user_order(
  TUO_ID INT AUTO_INCREMENT,
  TU_ID INT NOT NULL,
  TO_ID INT NOT NULL,
  TUO_DETAIL VARCHAR(100),
  PRIMARY KEY(TUO_ID),
  FOREIGN KEY(TU_ID) REFERENCES tbl_user(TU_ID),
  FOREIGN KEY(TO_ID) REFERENCES tbl_order(TO_ID)
) ENGINE=InnoDB AUTO_INCREMENT=100001 DEFAULT CHARSET=utf8;
